spring:
  application:
    name: BackendBase
  H2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1
    initialize: true
    sql-script-encoding: UTF-8
    username: sa
    password: sa
  jpa:
    #database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      fail-on-empty-beans: false
      INDENT_OUTPUT: true
server:
  servlet:
    context-path: /BackendBase
    port: 8080

# 系統自訂參數
app:
  jwt-secret: Xnnl4virliz0BzJnGAdsE6spyZvOU3d7
  jwt-issuer: base